version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: cresceja_postgres
    environment:
      POSTGRES_USER: cresceja
      POSTGRES_PASSWORD: cresceja123
      POSTGRES_DB: cresceja_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: cresceja_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: